version: '3'

services:

  ##############
  # swagger-ui #
  ##############
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:v3.19.3
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:3000/
    restart: always