version: '3'

services:
  db:
    container_name: db
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      # anything in initdb directory is created in the database
      # see "How to extend this image" section at https://hub.docker.com/r/_/postgres/
      - "./initdb:/docker-entrypoint-initdb.d"
    restart: always

  postgrest:
    container_name: postgrest
    image: begriffs/postgrest:v0.4.1.0
    ports:
      - "3000:3000"
    volumes:
      - "./postgrest.conf:/etc/postgrest.conf"
    restart: always